import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[url(/body-background.webp)] bg-cover`}
      >
        <ThemeProvider
          attribute="class"
          forcedTheme="dark"
          storageKey="place4stream-theme"
        >
          <div className="w-full h-full backdrop-brightness-75 absolute top-0 right-0" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
